services:
  server1:
    image: server1:latest
    build: ./serverOne/.
    ports:
      - "8080:8080"
    networks:
      - web-network

  server2:
    image: server2:latest
    build: ./serverTwo/.
    ports:
      - "8081:8081"
    networks:
      - web-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - web-network
    depends_on:
      - server1
      - server2

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: prometheus-nginx-exporter
    restart: always
    command:
      - -nginx.scrape-uri=http://nginx:80/metrics
    ports:
      - "9113:9113"
    networks:
      - web-network
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - web-network
    depends_on:
      - nginx-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus
    networks:
      - web-network

networks:
  web-network:
    driver: bridge

