global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    metrics_path: "/"
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'web-server'
    static_configs:
      - targets: ['server1:80', 'server2:80']