apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Cambia 'prometheus' por el nombre del contenedor de Prometheus
    isDefault: true